<a href="https://colab.research.google.com/github/Meenakshigupta6527/Data-Acquisition-Data-wrangling/blob/main/Data_Acquisition_Data_Wrangling.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
dataset_1=pd.read_excel('/content/drive/MyDrive/Internship_Project2/dataset_1.xlsx')

In [ ]:
dataset_1

instant     dteday  season  yr  mnth  hr  holiday  weekday  weathersit  \
0          1 2011-01-01       1   0     1   0    False        6           1   
1          2 2011-01-01       1   0     1   1    False        6           1   
2          3 2011-01-01       1   0     1   2    False        6           1   
3          4 2011-01-01       1   0     1   3    False        6           1   
4          5 2011-01-01       1   0     1   4    False        6           1   
..       ...        ...     ...  ..   ...  ..      ...      ...         ...   
605      606 2011-01-28       1   0     1  11    False        5           3   
606      607 2011-01-28       1   0     1  12    False        5           3   
607      608 2011-01-28       1   0     1  13    False        5           3   
608      609 2011-01-28       1   0     1  14    False        5           3   
609      610 2011-01-28       1   0     1  15    False        5           2   

     temp  
0    0.24  
1    0.22  
2    0.22  
3    0.24  
4    0.24  
..    ...  
605  0.18  
606  0.18  
607  0.18  
608  0.22  
609  0.20  

[610 rows x 10 columns]

In [ ]:
dataset_1['season'].unique()

array([1])

In [ ]:
dataset_1.drop(['season'],axis=1,inplace=True)

In [ ]:
dataset_1

instant     dteday  yr  mnth  hr  holiday  weekday  weathersit  temp
0          1 2011-01-01   0     1   0    False        6           1  0.24
1          2 2011-01-01   0     1   1    False        6           1  0.22
2          3 2011-01-01   0     1   2    False        6           1  0.22
3          4 2011-01-01   0     1   3    False        6           1  0.24
4          5 2011-01-01   0     1   4    False        6           1  0.24
..       ...        ...  ..   ...  ..      ...      ...         ...   ...
605      606 2011-01-28   0     1  11    False        5           3  0.18
606      607 2011-01-28   0     1  12    False        5           3  0.18
607      608 2011-01-28   0     1  13    False        5           3  0.18
608      609 2011-01-28   0     1  14    False        5           3  0.22
609      610 2011-01-28   0     1  15    False        5           2  0.20

[610 rows x 9 columns]

In [ ]:
dataset_1['mnth'].unique()

array([1])

In [ ]:
dataset_1.drop(['mnth'],axis=1,inplace=True)

In [ ]:
dataset_1

instant     dteday  yr  hr  holiday  weekday  weathersit  temp
0          1 2011-01-01   0   0    False        6           1  0.24
1          2 2011-01-01   0   1    False        6           1  0.22
2          3 2011-01-01   0   2    False        6           1  0.22
3          4 2011-01-01   0   3    False        6           1  0.24
4          5 2011-01-01   0   4    False        6           1  0.24
..       ...        ...  ..  ..      ...      ...         ...   ...
605      606 2011-01-28   0  11    False        5           3  0.18
606      607 2011-01-28   0  12    False        5           3  0.18
607      608 2011-01-28   0  13    False        5           3  0.18
608      609 2011-01-28   0  14    False        5           3  0.22
609      610 2011-01-28   0  15    False        5           2  0.20

[610 rows x 8 columns]

In [ ]:
dataset_1['yr'].unique()

array([0])

In [ ]:
dataset_1.drop(['yr'],axis=1,inplace=True)
dataset_1

instant     dteday  hr  holiday  weekday  weathersit  temp
0          1 2011-01-01   0    False        6           1  0.24
1          2 2011-01-01   1    False        6           1  0.22
2          3 2011-01-01   2    False        6           1  0.22
3          4 2011-01-01   3    False        6           1  0.24
4          5 2011-01-01   4    False        6           1  0.24
..       ...        ...  ..      ...      ...         ...   ...
605      606 2011-01-28  11    False        5           3  0.18
606      607 2011-01-28  12    False        5           3  0.18
607      608 2011-01-28  13    False        5           3  0.18
608      609 2011-01-28  14    False        5           3  0.22
609      610 2011-01-28  15    False        5           2  0.20

[610 rows x 7 columns]

In [ ]:
dataset_1['holiday'].unique()

array([False,  True])

In [ ]:
dataset_1.dtypes

instant                int64
dteday        datetime64[ns]
hr                     int64
holiday                 bool
weekday                int64
weathersit             int64
temp                 float64
dtype: object

In [ ]:
dataset_1['holiday']=dataset_1['holiday'].astype(int)
dataset_1.dtypes

instant                int64
dteday        datetime64[ns]
hr                     int64
holiday                int64
weekday                int64
weathersit             int64
temp                 float64
dtype: object

In [ ]:
dataset_1

instant     dteday  hr  holiday  weekday  weathersit  temp
0          1 2011-01-01   0        0        6           1  0.24
1          2 2011-01-01   1        0        6           1  0.22
2          3 2011-01-01   2        0        6           1  0.22
3          4 2011-01-01   3        0        6           1  0.24
4          5 2011-01-01   4        0        6           1  0.24
..       ...        ...  ..      ...      ...         ...   ...
605      606 2011-01-28  11        0        5           3  0.18
606      607 2011-01-28  12        0        5           3  0.18
607      608 2011-01-28  13        0        5           3  0.18
608      609 2011-01-28  14        0        5           3  0.22
609      610 2011-01-28  15        0        5           2  0.20

[610 rows x 7 columns]

In [ ]:
dataset_1['holiday'].unique()

array([0, 1])

In [ ]:
dataset_1.duplicated().sum()

0

In [ ]:
dataset_1.isnull().sum()

instant       0
dteday        0
hr            0
holiday       0
weekday       0
weathersit    0
temp          0
dtype: int64

In [ ]:
dataset_1.shape

(610, 7)

In [ ]:
dataset_2=pd.read_excel('/content/drive/MyDrive/Internship_Project2/dataset_2.xlsx')

In [ ]:
dataset_2

Unnamed: 0  instant   atemp   hum  windspeed  casual  registered  cnt
0             0        1  0.2879  0.81     0.0000       3          13   16
1             1        2  0.2727  0.80     0.0000       8          32   40
2             2        3  0.2727  0.80     0.0000       5          27   32
3             3        4  0.2879  0.75     0.0000       3          10   13
4             4        5  0.2879  0.75     0.0000       0           1    1
..          ...      ...     ...   ...        ...     ...         ...  ...
605         605      606  0.2121  0.93     0.1045       0          30   30
606         606      607  0.2121  0.93     0.1045       1          28   29
607         607      608  0.2121  0.93     0.1045       0          31   31
608         608      609  0.2727  0.80     0.0000       2          36   38
609         609      610  0.2576  0.86     0.0000       1          40   41

[610 rows x 8 columns]

In [ ]:
dataset_2.drop(['Unnamed: 0'],axis=1,inplace=True)

In [ ]:
dataset_2

instant   atemp   hum  windspeed  casual  registered  cnt
0          1  0.2879  0.81     0.0000       3          13   16
1          2  0.2727  0.80     0.0000       8          32   40
2          3  0.2727  0.80     0.0000       5          27   32
3          4  0.2879  0.75     0.0000       3          10   13
4          5  0.2879  0.75     0.0000       0           1    1
..       ...     ...   ...        ...     ...         ...  ...
605      606  0.2121  0.93     0.1045       0          30   30
606      607  0.2121  0.93     0.1045       1          28   29
607      608  0.2121  0.93     0.1045       0          31   31
608      609  0.2727  0.80     0.0000       2          36   38
609      610  0.2576  0.86     0.0000       1          40   41

[610 rows x 7 columns]

In [ ]:
dataset_2.dtypes

instant         int64
atemp         float64
hum           float64
windspeed     float64
casual          int64
registered      int64
cnt             int64
dtype: object

In [ ]:
dataset_2.duplicated().sum()

0

In [ ]:
dataset_2.isnull().sum()

instant        0
atemp         11
hum            0
windspeed      0
casual         0
registered     0
cnt            0
dtype: int64

In [ ]:
dataset_2.describe()

instant       atemp         hum   windspeed      casual  registered  \
count  610.000000  599.000000  610.000000  610.000000  610.000000  610.000000   
mean   305.500000    0.199935    0.562475    0.204851    4.501639   51.068852   
std    176.236111    0.078836    0.175440    0.121806    6.319945   47.021204   
min      1.000000    0.000000    0.210000    0.000000    0.000000    0.000000   
25%    153.250000    0.151500    0.432500    0.104500    0.000000   14.000000   
50%    305.500000    0.197000    0.520000    0.194000    2.000000   43.000000   
75%    457.750000    0.242400    0.690000    0.283600    6.000000   70.000000   
max    610.000000    0.454500    1.000000    0.582100   47.000000  247.000000   

              cnt  
count  610.000000  
mean    55.570492  
std     49.316802  
min      1.000000  
25%     16.000000  
50%     47.000000  
75%     79.750000  
max    249.000000

In [ ]:
combine_data= pd.merge(dataset_1,dataset_2,on='instant',how='inner')
combine_data

instant     dteday  hr  holiday  weekday  weathersit  temp   atemp   hum  \
0          1 2011-01-01   0        0        6           1  0.24  0.2879  0.81   
1          2 2011-01-01   1        0        6           1  0.22  0.2727  0.80   
2          3 2011-01-01   2        0        6           1  0.22  0.2727  0.80   
3          4 2011-01-01   3        0        6           1  0.24  0.2879  0.75   
4          5 2011-01-01   4        0        6           1  0.24  0.2879  0.75   
..       ...        ...  ..      ...      ...         ...   ...     ...   ...   
605      606 2011-01-28  11        0        5           3  0.18  0.2121  0.93   
606      607 2011-01-28  12        0        5           3  0.18  0.2121  0.93   
607      608 2011-01-28  13        0        5           3  0.18  0.2121  0.93   
608      609 2011-01-28  14        0        5           3  0.22  0.2727  0.80   
609      610 2011-01-28  15        0        5           2  0.20  0.2576  0.86   

     windspeed  casual  registered  cnt  
0       0.0000       3          13   16  
1       0.0000       8          32   40  
2       0.0000       5          27   32  
3       0.0000       3          10   13  
4       0.0000       0           1    1  
..         ...     ...         ...  ...  
605     0.1045       0          30   30  
606     0.1045       1          28   29  
607     0.1045       0          31   31  
608     0.0000       2          36   38  
609     0.0000       1          40   41  

[610 rows x 13 columns]

In [ ]:
combine_data.shape

(610, 13)

In [ ]:
combine_data.dtypes

instant                int64
dteday        datetime64[ns]
hr                     int64
holiday                int64
weekday                int64
weathersit             int64
temp                 float64
atemp                float64
hum                  float64
windspeed            float64
casual                 int64
registered             int64
cnt                    int64
dtype: object

In [ ]:
combine_data.duplicated().sum()

0

In [ ]:
combine_data.isnull().sum()

instant        0
dteday         0
hr             0
holiday        0
weekday        0
weathersit     0
temp           0
atemp         11
hum            0
windspeed      0
casual         0
registered     0
cnt            0
dtype: int64

In [ ]:
combine_data['atemp'].replace('?',np.nan,inplace=True)

In [ ]:
combine_data

instant     dteday  hr  holiday  weekday  weathersit  temp   atemp   hum  \
0          1 2011-01-01   0        0        6           1  0.24  0.2879  0.81   
1          2 2011-01-01   1        0        6           1  0.22  0.2727  0.80   
2          3 2011-01-01   2        0        6           1  0.22  0.2727  0.80   
3          4 2011-01-01   3        0        6           1  0.24  0.2879  0.75   
4          5 2011-01-01   4        0        6           1  0.24  0.2879  0.75   
..       ...        ...  ..      ...      ...         ...   ...     ...   ...   
605      606 2011-01-28  11        0        5           3  0.18  0.2121  0.93   
606      607 2011-01-28  12        0        5           3  0.18  0.2121  0.93   
607      608 2011-01-28  13        0        5           3  0.18  0.2121  0.93   
608      609 2011-01-28  14        0        5           3  0.22  0.2727  0.80   
609      610 2011-01-28  15        0        5           2  0.20  0.2576  0.86   

     windspeed  casual  registered  cnt  
0       0.0000       3          13   16  
1       0.0000       8          32   40  
2       0.0000       5          27   32  
3       0.0000       3          10   13  
4       0.0000       0           1    1  
..         ...     ...         ...  ...  
605     0.1045       0          30   30  
606     0.1045       1          28   29  
607     0.1045       0          31   31  
608     0.0000       2          36   38  
609     0.0000       1          40   41  

[610 rows x 13 columns]

In [ ]:
combine_data['atemp'].unique()

array([0.2879, 0.2727, 0.2576,    nan, 0.3485, 0.3939, 0.3333, 0.4242,
       0.4545, 0.4394, 0.4091, 0.2273, 0.2121, 0.197 , 0.1364, 0.1061,
       0.1212, 0.1667, 0.1818, 0.2424, 0.1515, 0.3182, 0.0606, 0.0758,
       0.0909, 0.303 , 0.0303, 0.0455, 0.    , 0.0152])

In [ ]:
combine_data['atemp'].isnull().sum()/combine_data['atemp'].shape[0]*100

1.8032786885245904

In [ ]:
combine_data['atemp'].mean()

0.19993489148580967

In [ ]:
combine_data['atemp'].median()

0.197